import type { EditorThemeClasses } from "lexical";

export const theme: EditorThemeClasses = {
  heading: {
    h1: "editor-h1",
    h2: "editor-h2",
    h3: "editor-h3",
  },
  list: {
    ul: "editor-ul",
    ol: "editor-ol",
    listitem: "editor-li",
    nested: {
      list: "editor-nested-list",
      listitem: "editor-nested-li",
    },
  },
  code: "editor-code",
  codeHighlight: {
    atrule: "editor-token-atrule",
    attr: "editor-token-attr",
    boolean: "editor-token-boolean",
    builtin: "editor-token-builtin",
    cdata: "editor-token-cdata",
    char: "editor-token-char",
    "class-name": "editor-token-class-name",
    comment: "editor-token-comment",
    constant: "editor-token-constant",
    deleted: "editor-token-deleted",
    doctype: "editor-token-doctype",
    entity: "editor-token-entity",
    function: "editor-token-function",
    important: "editor-token-important",
    inserted: "editor-token-inserted",
    keyword: "editor-token-keyword",
    namespace: "editor-token-variable",
    number: "editor-token-number",
    operator: "editor-token-operator",
    prolog: "editor-token-prolog",
    property: "editor-token-property",
    punctuation: "editor-token-punctuation",
    regex: "editor-token-regex",
    selector: "editor-token-selector",
    string: "editor-token-string",
    symbol: "editor-token-symbol",
    tag: "editor-token-tag",
    url: "editor-token-url",
    variable: "editor-token-variable",
  },
  text: {
    bold: "editor-bold",
    italic: "editor-italic",
    strikethrough: "editor-strike",
    underline: "editor-underline",
    code: "editor-inline-code",
  },
  paragraph: "editor-paragraph",
  quote: "editor-quote",
  hr: "editor-hr",
};
